output.logstash:
  enabled: true #´ò¿ªÊä³ö
  hosts: ["elk:5044"]
  ssl:
      certificate_authorities:
        - /etc/pki/tls/certs/logstash-beats.crt
  timeout: 15

filebeat.prospectors:
  - 
    paths:
      - /var/log/syslog
      - /var/log/auth.log
    input_type: log
    document_type: syslog    